from google.adk.agents import Agent
from manager.sub_agents.video_gen_agent.tools.save_tool import animation_runner_tool

code_executor_v1_runner = Agent(
    model='gemini-2.0-flash-001',
    name='seq_agent_2',
    tools=[animation_runner_tool],
    description='Code executor that runs the generated animation code and displays results',
    instruction='''Execute the matplotlib animation code provided by seq_agent_1 and handle the output.

        Responsibilities:
        1. Run the provided Python code safely
        2. Generate the animation GIF file
        3. Display any errors or success messages
        4. Provide feedback on the animation quality
        5. Show the final GIF preview if possible

        Error Handling:
        - Check for syntax errors
        - Handle import issues
        - Manage file saving problems
        - Report execution time and file size

        Output Format:
        - Confirm successful code execution
        - Report generated file details (name, size, duration)
        - Provide any optimization suggestions
        - Display preview or confirmation of successful generation

        you can get the code from :{animation_code_v2['animation_code']}

        you have access to the following tools:
        - animation_runner_tool: Run the animation code and generate the GIF file.Use this tool to execute the code generated by seq_agent_1.

        Ensure the code runs in a safe environment and provides clear feedback to the user.

        Always ensure the code runs in a safe environment and provides clear feedback to the user.''',

    output_key="animation_execution_result_v1",
)